workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - restore_cache:
          key: deps-npm-{{ .Branch }}-{{ checksum "package.json" }}
      - restore_cache:
          key: deps-bower-{{ .Branch }}-{{ checksum "bower.json" }}
      - save_cache:
          key: deps-npm-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - save_cache:
          key: deps-bower-{{ .Branch }}-{{ checksum "bower.json" }}
          paths:
            - "app/bower_components"
      - run:
          command: |
            npm install
            node_modules/.bin/jshint www/js
            node_modules/karma/bin/karma start tests/karma.conf.js --single-run
            node_modules/coveralls/bin/coveralls.js < tests/coverage/PhantomJS*/lcov.info
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/eggtimer-ui.git master
